project:
  type: website

website:
  title: "SIPBS CompBio PDA Pages"
  site-url: https://sipbs-compbiol.github.io/sipbscompbiol-pda
  navbar:
    logo: ./assets/images/sipbs_compbio.png
    right:
      - text: "Home"
        file: index.qmd
      - text: "PDA Info"
        menu: 
          - text: "Key Dates"
            href: calendar.qmd
      - text: "Resources"
        menu:
          - text: "Time Management"
            href: time_management.qmd
          - text: "Learning Resources"
            href: learning_resources.qmd
          - text: "Software Tools"
            href: software.qmd
          - text: "Giving Scientific Presentations"
            href: presentation.qmd
          - text: "Science Communication"
            href: scicomm.qmd
      - icon: github
        href: https://github.com/sipbs-compbiol/sipbscompbiol-pda
      - icon: twitter
        href: https://twitter.com/scompbiol
      - icon: rss
        href: index.xml  
  page-footer: 
    left: This site © University of Strathclyde 2023


format:
  html:
    theme: simplex
    toc: true
    css: styles.css
    embed-resources: true

editor: source

execute:
  freeze: auto
